# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.1
_src_path: https://github.com/wabenet/copier-dodo-plugin
author_email: ole.claussen@wabenet.com
author_name: Ole Claussen
description: Adds support for VirtualBox as a dodo stage plugin.
go_version: '1.18'
is_standalone: true
lifecycle: experimental
name: stage-virtualbox
use_protobuf: false

